language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  
services:
  - mysql
  
before_install:
  # WP-CLI: Install
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - sudo mv wp-cli.phar /usr/local/bin/wp
  
  # MYSQL: Install test DB
  - mysql -e 'CREATE DATABASE test;'

  # COMPOSER: Install
  - composer install --dev

  # WP-CLI: Install Core
  - wp core install
  
  # WP-CLI: Activate Plugins
  - wp plugin activate --all
  
